# fly.toml app configuration file generated for parkit-holy-night-6483 on 2024-11-04T20:00:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'parkit-holy-night-6483'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
